SELECT B.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE < '2022-02-01'
GROUP BY B.AUTHOR_ID,B.CATEGORY,A.AUTHOR_NAME
ORDER BY B.AUTHOR_ID ASC,B.CATEGORY DESC