# 7월 아이스크림 총 주문량(JULY 테이블)과
# 상반기 아이스크림 총 주문량(FIRST_HALF) 더하기
# 큰 순서대로 상위 3개 조회(FLAVOR)


SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
) J
ON FH.FLAVOR = J.FLAVOR
ORDER BY FH.TOTAL_ORDER + J.JULY_TOTAL DESC
LIMIT 3